"""
Motion API Connector (UseMotion.com Task & Career Intelligence Sync)
=====================================================================
Provides integration with Motion (https://www.usemotion.com) for automated
task scheduling, interview prep deadlines, job application tracking, and calendar sync.

Motion REST API v1 Base URL: https://api.usemotion.com/v1
Authentication: Header 'X-API-Key' using MOTION_API_KEY from environment.
"""

from __future__ import annotations
import os
import json
import logging
import urllib.request
import urllib.error
from dataclasses import dataclass, asdict
from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta

logger = logging.getLogger("job_agent.motion")

MOTION_API_BASE = "https://api.usemotion.com/v1"


@dataclass
class MotionTask:
    name: str
    description: Optional[str] = None
    duration: int = 30  # duration in minutes (or 'REMINDER')
    dueDate: Optional[str] = None  # ISO 8601 string
    workspaceId: Optional[str] = None
    priority: str = "MEDIUM"  # LOW, MEDIUM, HIGH, URGENT
    autoScheduled: Optional[Dict[str, Any]] = None


class MotionConnector:
    """Connector for Motion (UseMotion.com) Task & Calendar Scheduling API."""
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("MOTION_API_KEY", "")
        self.headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "X-API-Key": self.api_key,
        }

    def is_configured(self) -> bool:
        """Returns True if MOTION_API_KEY is available."""
        return bool(self.api_key)

    def create_task(
        self,
        name: str,
        description: str = "",
        duration_minutes: int = 30,
        due_date_iso: Optional[str] = None,
        workspace_id: Optional[str] = None,
        priority: str = "MEDIUM"
    ) -> Dict[str, Any]:
        """Create a scheduled task in Motion."""
        if not due_date_iso:
            due_date_iso = (datetime.utcnow() + timedelta(days=3)).strftime("%Y-%m-%dT%H:%M:%SZ")

        payload = {
            "name": name,
            "description": description,
            "duration": duration_minutes,
            "dueDate": due_date_iso,
            "priority": priority
        }
        if workspace_id:
            payload["workspaceId"] = workspace_id

        if not self.is_configured():
            logger.info(f"[Motion Simulator] Simulated task creation: {name} (Due: {due_date_iso})")
            return {
                "id": "simulated-motion-task-101",
                "name": name,
                "status": "SIMULATED_SUCCESS",
                "dueDate": due_date_iso,
                "message": "Task queued in local Motion simulator (Set MOTION_API_KEY for live API sync)"
            }

        req = urllib.request.Request(
            f"{MOTION_API_BASE}/tasks",
            data=json.dumps(payload).encode("utf-8"),
            headers=self.headers,
            method="POST"
        )

        try:
            with urllib.request.urlopen(req, timeout=10) as response:
                res_data = json.loads(response.read().decode("utf-8"))
                logger.info(f"Motion Task Created: {res_data.get('id')}")
                return res_data
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8")
            logger.error(f"Motion API Error ({e.code}): {err_msg}")
            return {"error": True, "code": e.code, "message": err_msg}
        except Exception as e:
            logger.error(f"Motion Network Error: {str(e)}")
            return {"error": True, "message": str(e)}

    def sync_application_deadline(self, job_title: str, company: str, deadline_days: int = 3) -> Dict[str, Any]:
        """Sync a job application follow-up deadline task to Motion."""
        due_date = (datetime.utcnow() + timedelta(days=deadline_days)).strftime("%Y-%m-%dT%H:%M:%SZ")
        task_name = f"Follow-up: {job_title} at {company}"
        description = f"Automated follow-up task generated by ResumeAgent for {job_title} position at {company}."
        return self.create_task(
            name=task_name,
            description=description,
            duration_minutes=30,
            due_date_iso=due_date,
            priority="HIGH"
        )
